// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_esmera_search from "./routes/api/esmera-search.ts";
import * as $colecao_slug_ from "./routes/colecao/[slug].tsx";
import * as $colecao_index from "./routes/colecao/index.tsx";
import * as $contato from "./routes/contato.tsx";
import * as $produto_slug_ from "./routes/produto/[slug].tsx";
import * as $sobre from "./routes/sobre.tsx";
import * as $EsmeraHeader from "./islands/EsmeraHeader.tsx";
import * as $EsmeraMotion from "./islands/EsmeraMotion.tsx";
import * as $EsmeraScrollScenes from "./islands/EsmeraScrollScenes.tsx";
import * as $HeroCarousel from "./islands/HeroCarousel.tsx";
import * as $ProductActions from "./islands/ProductActions.tsx";
import * as $SpatialMatter from "./islands/SpatialMatter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/esmera-search.ts": $api_esmera_search,
    "./routes/colecao/[slug].tsx": $colecao_slug_,
    "./routes/colecao/index.tsx": $colecao_index,
    "./routes/contato.tsx": $contato,
    "./routes/produto/[slug].tsx": $produto_slug_,
    "./routes/sobre.tsx": $sobre,
  },
  islands: {
    "./islands/EsmeraHeader.tsx": $EsmeraHeader,
    "./islands/EsmeraMotion.tsx": $EsmeraMotion,
    "./islands/EsmeraScrollScenes.tsx": $EsmeraScrollScenes,
    "./islands/HeroCarousel.tsx": $HeroCarousel,
    "./islands/ProductActions.tsx": $ProductActions,
    "./islands/SpatialMatter.tsx": $SpatialMatter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
