// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/Esmera/About.ts";
import * as $$$1 from "./loaders/Esmera/CategoryBySlug.ts";
import * as $$$2 from "./loaders/Esmera/CategoryList.ts";
import * as $$$3 from "./loaders/Esmera/CollectionPage.ts";
import * as $$$4 from "./loaders/Esmera/Contact.ts";
import * as $$$5 from "./loaders/Esmera/Home.ts";
import * as $$$6 from "./loaders/Esmera/Navigation.ts";
import * as $$$7 from "./loaders/Esmera/ProductBySlug.ts";
import * as $$$8 from "./loaders/Esmera/ProductList.ts";
import * as $$$9 from "./loaders/Esmera/ProductsByCategory.ts";
import * as $$$10 from "./loaders/Esmera/SearchProducts.ts";
import * as $$$11 from "./loaders/Esmera/SiteSettings.ts";
import * as $$$12 from "./loaders/Esmera/StorefrontPageData.ts";
import * as $$$$$$0 from "./sections/Esmera/Collection.tsx";
import * as $$$$$$1 from "./sections/Esmera/Context.tsx";
import * as $$$$$$2 from "./sections/Esmera/Footer.tsx";
import * as $$$$$$3 from "./sections/Esmera/Header.tsx";
import * as $$$$$$4 from "./sections/Esmera/Hero.tsx";
import * as $$$$$$5 from "./sections/Esmera/Manifesto.tsx";
import * as $$$$$$6 from "./sections/Esmera/Matter.tsx";
import * as $$$$$$7 from "./sections/Esmera/MatterInterlude.tsx";
import * as $$$$$$8 from "./sections/Esmera/PayloadHome.tsx";
import * as $$$$$$9 from "./sections/Esmera/PrivateInvitation.tsx";
import * as $$$$$$10 from "./sections/Esmera/Provenance.tsx";
import * as $$$$$$11 from "./sections/Esmera/SelectedObjects.tsx";
import * as $$$$$$12 from "./sections/Esmera/SignatureObject.tsx";
import * as $$$$$$13 from "./sections/Footer.tsx";
import * as $$$$$$14 from "./sections/ItWorks.tsx";
import * as $$$$$$15 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/Esmera/About.ts": $$$0,
    "site/loaders/Esmera/CategoryBySlug.ts": $$$1,
    "site/loaders/Esmera/CategoryList.ts": $$$2,
    "site/loaders/Esmera/CollectionPage.ts": $$$3,
    "site/loaders/Esmera/Contact.ts": $$$4,
    "site/loaders/Esmera/Home.ts": $$$5,
    "site/loaders/Esmera/Navigation.ts": $$$6,
    "site/loaders/Esmera/ProductBySlug.ts": $$$7,
    "site/loaders/Esmera/ProductList.ts": $$$8,
    "site/loaders/Esmera/ProductsByCategory.ts": $$$9,
    "site/loaders/Esmera/SearchProducts.ts": $$$10,
    "site/loaders/Esmera/SiteSettings.ts": $$$11,
    "site/loaders/Esmera/StorefrontPageData.ts": $$$12,
  },
  "sections": {
    "site/sections/Esmera/Collection.tsx": $$$$$$0,
    "site/sections/Esmera/Context.tsx": $$$$$$1,
    "site/sections/Esmera/Footer.tsx": $$$$$$2,
    "site/sections/Esmera/Header.tsx": $$$$$$3,
    "site/sections/Esmera/Hero.tsx": $$$$$$4,
    "site/sections/Esmera/Manifesto.tsx": $$$$$$5,
    "site/sections/Esmera/Matter.tsx": $$$$$$6,
    "site/sections/Esmera/MatterInterlude.tsx": $$$$$$7,
    "site/sections/Esmera/PayloadHome.tsx": $$$$$$8,
    "site/sections/Esmera/PrivateInvitation.tsx": $$$$$$9,
    "site/sections/Esmera/Provenance.tsx": $$$$$$10,
    "site/sections/Esmera/SelectedObjects.tsx": $$$$$$11,
    "site/sections/Esmera/SignatureObject.tsx": $$$$$$12,
    "site/sections/Footer.tsx": $$$$$$13,
    "site/sections/ItWorks.tsx": $$$$$$14,
    "site/sections/Theme/Theme.tsx": $$$$$$15,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
