// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Esmera/Collection.tsx";
import * as $$$$$$1 from "./sections/Esmera/Context.tsx";
import * as $$$$$$2 from "./sections/Esmera/Footer.tsx";
import * as $$$$$$3 from "./sections/Esmera/Header.tsx";
import * as $$$$$$4 from "./sections/Esmera/Hero.tsx";
import * as $$$$$$5 from "./sections/Esmera/Manifesto.tsx";
import * as $$$$$$6 from "./sections/Esmera/Matter.tsx";
import * as $$$$$$7 from "./sections/Esmera/PrivateInvitation.tsx";
import * as $$$$$$8 from "./sections/Esmera/Process.tsx";
import * as $$$$$$9 from "./sections/Esmera/Provenance.tsx";
import * as $$$$$$10 from "./sections/Esmera/SelectedObjects.tsx";
import * as $$$$$$11 from "./sections/Esmera/SignatureObject.tsx";
import * as $$$$$$12 from "./sections/Footer.tsx";
import * as $$$$$$13 from "./sections/ItWorks.tsx";
import * as $$$$$$14 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Esmera/Collection.tsx": $$$$$$0,
    "site/sections/Esmera/Context.tsx": $$$$$$1,
    "site/sections/Esmera/Footer.tsx": $$$$$$2,
    "site/sections/Esmera/Header.tsx": $$$$$$3,
    "site/sections/Esmera/Hero.tsx": $$$$$$4,
    "site/sections/Esmera/Manifesto.tsx": $$$$$$5,
    "site/sections/Esmera/Matter.tsx": $$$$$$6,
    "site/sections/Esmera/PrivateInvitation.tsx": $$$$$$7,
    "site/sections/Esmera/Process.tsx": $$$$$$8,
    "site/sections/Esmera/Provenance.tsx": $$$$$$9,
    "site/sections/Esmera/SelectedObjects.tsx": $$$$$$10,
    "site/sections/Esmera/SignatureObject.tsx": $$$$$$11,
    "site/sections/Footer.tsx": $$$$$$12,
    "site/sections/ItWorks.tsx": $$$$$$13,
    "site/sections/Theme/Theme.tsx": $$$$$$14,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
